# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Fetch misato binary
        run: |
          wget https://github.com/flyingcakes85/misato/releases/download/v0.1.0_testing/misato
          chmod +x misato

      - name: Build
        run: ./misato build

      - name: Push to remote
        run: |
          cd target
          git config --global init.defaultBranch gh-pages
          git init
          git config --global user.name "GitHub Actions"
          git config --global user.name "github-action-bot@users.noreply.github.com"
          git add .
          git commit -m "Build website"
          git remote add origin http://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/flyingcakes85/misato-demo
          git push --force -u origin gh-pages
